function targetEvent(event) {
  return {
    ...event,
    why: event.whyWheeler,
    firstAction: event.firstActionThisWeek,
    weekly: event.weeklyTraining,
    evidence: event.evidenceToCollect,
    mistakes: event.commonMistakes,
  }
}

export const FINAL_EVENT_BATCH = [
  targetEvent({
    id: 'research-poster',
    name: 'Research Poster',
    track: 'Research, Poster, and Presentation',
    format: 'Poster research and presentation',
    team: 'Verify in guideline',
    difficulty: 'Medium to High',
    commitment: 'High commitment',
    time: 5,
    bestFor: ['research', 'science', 'writing', 'design', 'speaking'],
    avoidIf: ['You do not want to read sources.', 'You will not revise a poster before competition.'],
    whyWheeler: 'A strong fit for students who can turn research into a clean poster and explain it clearly.',
    firstActionThisWeek: 'Pick one focused health research question and list five credible sources before designing anything.',
    weeklyTraining: ['Choose a narrow research question.', 'Collect source notes.', 'Draft poster sections.', 'Get feedback on visual clarity.', 'Practice a two-minute explanation.'],
    evidenceToCollect: ['Research question', 'Source notes', 'Poster draft', 'Feedback log', 'Upload checklist'],
    commonMistakes: ['Poster has too much text', 'Research question is vague', 'Weak source quality', 'No presentation practice'],
    officerCoaching: ['Check the research question before design starts.', 'Review poster readability.', 'Run a short poster defense.'],
  }),
  targetEvent({
    id: 'researched-persuasive-writing-speaking',
    name: 'Researched Persuasive Writing and Speaking',
    track: 'Research, Writing, and Speech',
    format: 'Paper and speech',
    team: 'Solo',
    difficulty: 'Medium to High',
    commitment: 'Serious',
    time: 5,
    bestFor: ['writing', 'research', 'speaking', 'policy', 'fast thinking'],
    avoidIf: ['You do not want to cite sources.', 'You dislike speaking after writing.'],
    whyWheeler: 'A good lane for strong writers who can defend a health position out loud.',
    firstActionThisWeek: 'Choose one health issue, write a claim, and find three credible sources for evidence and counterpoints.',
    weeklyTraining: ['Build a source bank.', 'Draft the paper early.', 'Turn the paper into a speech outline.', 'Practice delivery.', 'Prepare judge questions.'],
    evidenceToCollect: ['Claim and outline', 'Source bank', 'Paper drafts', 'Speech recording', 'Feedback notes'],
    commonMistakes: ['Opinion without evidence', 'Paper and speech do not match', 'Weak citations', 'No rebuttal prep'],
    officerCoaching: ['Check source credibility.', 'Listen for clear persuasion.', 'Ask counterargument questions.'],
  }),
  targetEvent({
    id: 'medical-reading',
    name: 'Medical Reading',
    track: 'Reading, Recall, and Health Science',
    format: 'Individual written test',
    team: 'Solo',
    difficulty: 'Medium',
    commitment: 'Serious',
    time: 4,
    bestFor: ['reading', 'memorization', 'health science', 'independent', 'test taking'],
    avoidIf: ['You will not read the assigned books.', 'You want a hands-on project.'],
    whyWheeler: 'A focused test event for students who can read steadily and remember important details.',
    firstActionThisWeek: 'Confirm the current reading list with the advisor and read the first assigned section with notes.',
    weeklyTraining: ['Read in short blocks.', 'Make chapter summaries.', 'Create character and concept notes if relevant.', 'Quiz key details.', 'Review missed questions.'],
    evidenceToCollect: ['Reading calendar', 'Chapter notes', 'Quiz scores', 'Missed detail list'],
    commonMistakes: ['Starting too late', 'Only reading summaries', 'No quiz practice', 'Forgetting names and details'],
    officerCoaching: ['Confirm the official reading list.', 'Check reading progress.', 'Run detail quizzes.'],
  }),
  targetEvent({
    id: 'healthcare-issues-exam',
    name: 'Healthcare Issues Exam',
    track: 'Current Events and Recognition',
    format: 'Individual recognition exam',
    team: 'Solo',
    difficulty: 'Medium',
    commitment: 'Low lift',
    time: 3,
    bestFor: ['current events', 'reading', 'policy', 'test taking', 'independent'],
    avoidIf: ['You do not follow health news.', 'You want a presentation event.'],
    whyWheeler: 'A practical recognition exam for students who already follow healthcare news and can review weekly.',
    firstActionThisWeek: 'Read three recent healthcare news articles and make a running current-events notes page.',
    weeklyTraining: ['Read health news weekly.', 'Summarize major policy changes.', 'Review healthcare organizations.', 'Take short current-events quizzes.', 'Update an example bank.'],
    evidenceToCollect: ['Article notes', 'Current-events log', 'Quiz scores', 'Example bank'],
    commonMistakes: ['Reading random news only', 'No dates or context', 'Ignoring healthcare policy', 'Cramming the week before'],
    officerCoaching: ['Share weekly article prompts.', 'Run current-events quizzes.', 'Clarify recognition rules with the advisor.'],
  }),
  targetEvent({
    id: 'medical-law-ethics',
    name: 'Medical Law and Ethics',
    track: 'Ethics, Law, and Healthcare Decisions',
    format: 'Individual written test',
    team: 'Solo',
    difficulty: 'Medium',
    commitment: 'Serious',
    time: 4,
    bestFor: ['ethics', 'policy', 'reading', 'memorization', 'test taking'],
    avoidIf: ['You dislike scenario-based questions.', 'You do not want to learn legal vocabulary.'],
    whyWheeler: 'A strong event for students who can think through rules, rights, responsibilities, and ethical choices.',
    firstActionThisWeek: 'Build a 40-term glossary for consent, confidentiality, liability, malpractice, and patient rights.',
    weeklyTraining: ['Study legal terms.', 'Practice ethics scenarios.', 'Compare similar terms.', 'Take timed quizzes.', 'Explain missed questions.'],
    evidenceToCollect: ['Glossary', 'Scenario notes', 'Quiz scores', 'Missed concept log'],
    commonMistakes: ['Memorizing terms without examples', 'Mixing up consent and confidentiality', 'Ignoring ethics principles', 'No timed practice'],
    officerCoaching: ['Ask scenario questions.', 'Check legal vocabulary.', 'Review missed-question explanations.'],
  }),
  targetEvent({
    id: 'epidemiology',
    name: 'Epidemiology',
    track: 'Disease Patterns and Public Health Data',
    format: 'Individual written test',
    team: 'Solo',
    difficulty: 'Medium to High',
    commitment: 'Serious',
    time: 4,
    bestFor: ['data', 'public health', 'science', 'analysis', 'test taking'],
    avoidIf: ['You dislike charts and data.', 'You do not want public health vocabulary.'],
    whyWheeler: 'A strong fit for students who like outbreaks, disease patterns, and evidence-based thinking.',
    firstActionThisWeek: 'Create a glossary for incidence, prevalence, outbreak, risk factor, surveillance, and study design.',
    weeklyTraining: ['Study core epidemiology terms.', 'Practice chart interpretation.', 'Work through outbreak examples.', 'Take timed quizzes.', 'Log missed data questions.'],
    evidenceToCollect: ['Glossary', 'Chart practice', 'Quiz scores', 'Outbreak case notes'],
    commonMistakes: ['Confusing incidence and prevalence', 'Skipping charts', 'Weak study design knowledge', 'Guessing from headlines'],
    officerCoaching: ['Review chart-reading strategies.', 'Assign outbreak examples.', 'Check missed data questions.'],
  }),
  targetEvent({
    id: 'nutrition',
    name: 'Nutrition',
    track: 'Nutrition, Wellness, and Health Science',
    format: 'Individual written test',
    team: 'Solo',
    difficulty: 'Medium',
    commitment: 'Serious',
    time: 4,
    bestFor: ['science', 'memorization', 'wellness', 'reading', 'test taking'],
    avoidIf: ['You do not want food science vocabulary.', 'You dislike memorizing nutrient functions.'],
    whyWheeler: 'A useful science test event for students interested in wellness, diet, and health education.',
    firstActionThisWeek: 'Make a nutrient chart for macronutrients, vitamins, minerals, functions, and deficiency examples.',
    weeklyTraining: ['Study nutrient functions.', 'Practice food label questions.', 'Review digestion and wellness concepts.', 'Take one timed quiz.', 'Keep an error log.'],
    evidenceToCollect: ['Nutrient chart', 'Food label practice', 'Quiz scores', 'Error log'],
    commonMistakes: ['Only memorizing food lists', 'Ignoring deficiency symptoms', 'No label practice', 'Mixing up vitamins and minerals'],
    officerCoaching: ['Quiz nutrient functions.', 'Use food-label examples.', 'Check the error log.'],
  }),
  targetEvent({
    id: 'human-growth-development',
    name: 'Human Growth and Development',
    track: 'Development, Life Stages, and Health',
    format: 'Individual written test',
    team: 'Solo',
    difficulty: 'Medium',
    commitment: 'Serious',
    time: 4,
    bestFor: ['psychology', 'memorization', 'reading', 'health science', 'test taking'],
    avoidIf: ['You dislike life-stage vocabulary.', 'You do not want developmental theory content.'],
    whyWheeler: 'A good event for students who like psychology, lifespan development, and health across ages.',
    firstActionThisWeek: 'Build a life-stage chart from infancy through older adulthood with major physical, cognitive, and social changes.',
    weeklyTraining: ['Study life stages.', 'Connect theories to examples.', 'Take short quizzes.', 'Explain missed concepts.', 'Review age-specific health needs.'],
    evidenceToCollect: ['Life-stage chart', 'Theory notes', 'Quiz scores', 'Missed concept log'],
    commonMistakes: ['Mixing up age ranges', 'Memorizing without examples', 'Ignoring social development', 'No review of missed questions'],
    officerCoaching: ['Ask stage comparison questions.', 'Review theory examples.', 'Check quiz trends.'],
  }),
  targetEvent({
    id: 'healthcare-administration',
    name: 'Healthcare Administration',
    track: 'Healthcare Systems and Management',
    format: 'Individual written test',
    team: 'Solo',
    difficulty: 'Medium',
    commitment: 'Serious',
    time: 4,
    bestFor: ['systems', 'business', 'policy', 'reading', 'test taking'],
    avoidIf: ['You only want clinical science content.', 'You dislike organization and management topics.'],
    whyWheeler: 'A good fit for students interested in how hospitals, clinics, teams, money, and policies work together.',
    firstActionThisWeek: 'Create a 50-term glossary on healthcare delivery, management, quality, finance, and patient safety.',
    weeklyTraining: ['Study system vocabulary.', 'Review healthcare roles.', 'Practice quality and safety scenarios.', 'Take timed quizzes.', 'Explain missed terms.'],
    evidenceToCollect: ['Glossary', 'Role map', 'Scenario notes', 'Quiz scores'],
    commonMistakes: ['Treating it like business only', 'Ignoring patient safety', 'Weak vocabulary', 'No timed practice'],
    officerCoaching: ['Review system diagrams.', 'Ask management scenario questions.', 'Track quiz improvement.'],
  }),
  targetEvent({
    id: 'health-career-photography',
    name: 'Health Career Photography',
    track: 'Career Exploration and Visual Storytelling',
    format: 'Photo portfolio and presentation',
    team: 'Solo',
    difficulty: 'Low to Medium',
    commitment: 'Serious',
    time: 4,
    bestFor: ['career', 'design', 'photography', 'speaking', 'research'],
    avoidIf: ['You do not want to plan ethical photos.', 'You will not practice explaining the career.'],
    whyWheeler: 'A creative career event for students who can research a health career and tell the story visually.',
    firstActionThisWeek: 'Choose one healthcare career and draft a photo plan that shows duties, skills, setting, and impact.',
    weeklyTraining: ['Research the career.', 'Plan photo concepts.', 'Take and select photos ethically.', 'Write captions.', 'Practice the presentation.'],
    evidenceToCollect: ['Career research notes', 'Photo plan', 'Draft portfolio', 'Caption drafts', 'Presentation notes'],
    commonMistakes: ['Random photos', 'Weak career research', 'No photo permissions', 'Captions do not explain the job'],
    officerCoaching: ['Review photo ethics.', 'Check career accuracy.', 'Run a presentation practice.'],
  }),
]
